services:
  - type: web
    name: myportfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myportfolio.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: MEDIA_ROOT
        value: /data/media
    disk:
      name: portfolio-data
      mountPath: /data
      sizeGB: 1

    # Add PostgreSQL database service
databases:
  - name: myportfolio_db
    plan: free
    ipAllowList: []  # only allow internal connections
