services:
  - type: web
    name: myportfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myportfolio.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      # The DATABASE_URL is defined below with the disk mount path
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    disk:
      name: portfolio-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/db.sqlite3
      - key: MEDIA_ROOT
        value: /data/media
