# Generated by Django 5.2 on 2025-04-28 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Project Image')),
                ('technologies_used', models.CharField(help_text='Enter technologies separated by commas', max_length=500, verbose_name='Technologies Used')),
                ('project_link', models.URLField(blank=True, null=True, verbose_name='Project URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
